source 'https://rubygems.org'

'rails/rails'
gem 'rails', '4.1.4'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',      group: :doc
gem 'spring',                group: :development

group :test, :development do
  gem "factory_girl_rails"
  gem "rspec-rails"
  gem 'shoulda-matchers'
end
